### ISSUE TITLE
Getting all black images

### ISSUE THREAD

**Issue by shreyaspimpalgaonkar** [tomography/tomobank#5]
The .tiff images that I got after running
     `python demo/tomopy_rec.py tomo_00007.h5 --axis 1232 --nsino 0.7`
are almost black.

After doing normalisation (normalising values between 0 and 255) I can see a big circle like here -

https://ibb.co/hPAsx8

**Comment by decarlof** [comment]
@shreyas-7 what you get is correct. These data are from nanoCT with low S/N plus because of a large load cell there are several blocked views ([141,226]).

**Comment by shreyaspimpalgaonkar** [comment]
Thanks, so how do I get [this](https://ibb.co/fSDnzo) image? - I have downloaded it from the tomohome website

Or maybe the left part of the image is same as my reconstruction?

**Comment by decarlof** [comment]
the left image is a projection (raw data transmission image at one angle); the right image is a reconstructed slice (output of tomopy_rec.py). This last is different from yours because you selected a different slice to be reconstructed (--nsino 0.7 => slice 1512 = 0.7 * ccd_y, in this case ccd_y = 2160)

**Comment by shreyaspimpalgaonkar** [comment]
Thank you. Also, for normalising the values, what was used to get that image?

I did -
    `img = img - min(img)`
    `img = img*255/max(img)`

min and max are minimum and maximum values of pixels in the image

**Comment by decarlof** [comment]
I assume img is the reconstructed slice, I think what you are doing will compress the dynamic range too much. Can you please give me the link to the downloadable tiff as generated by tomopy for img? I want to repeat the reconstruction and compare.

**Comment by shreyaspimpalgaonkar** [comment]
[Here](https://drive.google.com/open?id=1A180qgReP_dC0WPA0AfzKWZkUVlVmdvd) are some of the reconstructions of the same. (They are in gaps of 10 slices each)

**Comment by decarlof** [comment]
[here](https://drive.google.com/open?id=11pTBkz7gOX1d4gHhAvTwI311D8eSFEz-) is a png image obtained by loading recon_01132.tiff into imageJ and using auto-rescaling (Image/Adjust/Brightness-contrast) option. In this way the number of bits is automatically adjusted, I think your rescaling forcing 8 bits is compressing the dynamic range too much. Again these are difficult images with low S/N.
