### ISSUE TITLE
the unit of the propagation distance

### ISSUE THREAD

**Issue by XYangXRay** [tomography/tomobank#6]
I found from the reconstruction script that the phase retrieval parameter of data 0067 is:
   # Phase retrieval for tomobank id 00067
    # sample_detector_distance = 308
    # detector_pixel_size_x = 1.4e-4
    # monochromator_energy = 55.0
As the API of tomopy, the  sample_detector_distance should be 308 cm. However, the API of tomobank shows 308mm. Which is the right parameter for this case?
Thank you.

**Comment by decarlof** [comment]
The sample to detector distance listed in tomobank are in mm, when running tomopy [retrieve_phase](https://tomopy.readthedocs.io/en/latest/api/tomopy.prep.phase.html?highlight=retrieve_phase) you should pass cm. I corrected the error [here](https://github.com/tomography/tomobank/commit/19f8447a6da5abad91d8ef3040070a79043fa32b). Thank you for your help!
