### ISSUE TITLE
missing package

### ISSUE THREAD

**Issue by decarlof** [tomography/tomobank#9]
`import rectv`

in tomopy_rectv.py fails. @math-vrn may you please add instructions on how to install it?

**Comment by nikitinvv** [comment]
I have added more description in docs/source/data/docs.data.dynamic.rst
I also moved this "import rectv" under "if method == 'tv':", so if one prefer reconstruction by gridrec, then rectv is not needed

**Comment by decarlof** [comment]
then why not consolidate = use the same script, we can chanhe the tv parameter as boolean with defaut =false

francesco

**Comment by nikitinvv** [comment]
done
